lapapp/auth.py
from flask import Blueprint, render_template, redirect, sessions, url_for, request, flash, session
from werkzeug.security import generate_password_hash, check_password_hash
from .models import User
from flask_login import login_user, logout_user, login_required
from .models import User
from . import db

auth = Blueprint('auth', __name__)

@auth.route('/login')
def login():
    return render_template('login.html')

@auth.route('/login', methods=['POST'])
def login_post():
    name = request.form.get('name')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False
    user = User.query.filter_by(name=name).first()
    if not user or not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login'))
    login_user(user, remember=remember)
    if 'next' in session:
        next = session['next']
        session.pop('next', None)
        return redirect(url_for(f'main.{next[1:]}'))
    return redirect(url_for('main.index'))

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

lapapp/main.py
from flask import render_template, Blueprint, redirect
from flask_login import login_required
from . import db

main = Blueprint('main', __name__)

@main.route('/live', methods=['GET'])
@login_required
def live():
    return render_template('live.html')

@main.route('/history', methods=['GET'])
def history():
    return render_template('history.html')

@main.route('/', methods=['GET'])
def index():
    return render_template('index.html')

@main.route('/docs', methods=['GET'])
@login_required
def docs():
    return render_template('docs.html')

lapapp/main/routes.py
from flask import render_template, Blueprint, redirect, url_for, request, make_response
from flask_login import login_required
from werkzeug.utils import find_modules
from ..models import Data
from .. import db
import json
from ..api.routes import getdata, getdataformatted
import os
import boto3
from botocore.exceptions import ClientError


class Storage:
    # "/home/ubuntu/flask_aws/lapapp/jsons/"
    folder_path = "/home/collin/Code/lapTimes/lapapp/jsons/"

    @staticmethod
    def store(file_name):
        path = os.path.join(Storage.folder_path, file_name)
        json_data = getdata()
        with open(path, "w") as FILE:
            json.dump(json_data, FILE, indent=4, separators=(",", ": "))

    @staticmethod
    def get(file_name):
        path = f"{Storage.folder_path}{file_name}"
        with open(path, "r") as FILE:
            all_data = json.load(FILE)["data"]
        real_times = []
        for idx, val in enumerate(all_data):
            if idx == 0:
                real_times.append([val[0], val[1], val[2], "N/A"])
            else:
                real_times.append(
                    [
                        val[0],
                        val[1],
                        val[2],
                        round((val[2] - all_data[idx - 1][2]), 6),
                    ]
                )
        return real_times

    @staticmethod
    def send_to_s3():
        s3_client = boto3.client("s3")
        for file in os.listdir(Storage.folder_path):
            file_path = os.path.join(Storage.folder_path, file)
            try:
                s3_client.upload_file(
                    file_path, "motorsportlaptimesbackupstorage", file
                )
            except ClientError as e:
                print(e)
                return "failure, check logs"
        return "success"


main = Blueprint("main", __name__, template_folder="templates", static_folder="static")


@main.route("/live", methods=["GET"])
@login_required
def live():
    return render_template("live.html")


@main.route("/live", methods=["POST"])
@login_required
def live_post():
    name = request.form.get("name")
    Storage.store(f"{name}.json")
    Data.query.delete()
    db.session.commit()
    return redirect(url_for("main.records"))


@main.route("/", methods=["GET"])
def index():
    return redirect(url_for("main.live"))


@main.route("/records", methods=["GET"])
@login_required
def records():
    files = os.listdir(Storage.folder_path)
    return render_template("records.html", files=files)


@main.route("/records", methods=["POST"])
@login_required
def records_post():
    record_name = [x for x in request.form.lists()][0][0]
    os.remove(os.path.join(Storage.folder_path, record_name))
    return redirect(url_for("main.records"))


@main.route("/records/<id>", methods=["GET"])
@login_required
def records_specific(id):
    return render_template("record.html", data=Storage.get(id), title=id)


@main.route("/records/<id>", methods=["POST"])
@login_required
def records_specific_post(id):
    new_name = f"{request.form.get('name')}.json"
    os.rename(
        os.path.join(Storage.folder_path, id),
        os.path.join(Storage.folder_path, new_name),
    )
    return redirect(new_name)


@main.route("/records/<id>/excel.csv", methods=["GET"])
def records_specific_excel(id):
    csv = "id, date, time, difference\n"
    for row in Storage.get(id):
        csv += f"{row[0]},{row[1]},{row[2]},{row[3]}\n"
    response = make_response(csv)
    cd = "attachment; filename=" + id + ".csv"
    response.headers["Content-Disposition"] = cd
    response.mimetype = "text/csv"
    return response


@main.route("/issue", methods=["GET"])
def issue():
    return render_template("issue.html")


@main.route("/backup_data", methods=["GET"])
def backup():
    status = Storage.send_to_s3()
    return status

lapapp/templates/base.html
<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Lap Times</title>
    <meta name="description" content="Displaying data in the web">
    <meta name="author" content="cm1800">

    <meta property="og:title" content="Data Analytics">
    <meta property="og:type" content="website">
    <meta property="og:url" content="localhost:5000">
    <meta property="og:description" content="Displaying data in the web">

    <link rel="icon" href="/favicon.ico">
    <link rel="stylesheet" href="{{ url_for('static', filename='bulma.min.css') }}">
    <script src="{{ url_for('static', filename='jquery-3.6.0.min.js') }}"></script>
</head>

<body">
  <script>
    $(document).ready(function() {
      $(".navbar-burger").click(function() {
        $(".navbar-burger").toggleClass("is-active");
        $(".navbar-menu").toggleClass("is-active");
      });
    });
  </script>
    <div class="box">
        <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <a class="navbar-item" href="{{ url_for('main.index') }}">
            <h2 class="title" style="color: #e37622">Motorsport Laptimes</h2>
          </a>
      
          <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>  
        </div>
      
        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start">
            <a class="navbar-item" href="{{ url_for('main.live') }}">
              Live Data
            </a>
            <a class="navbar-item" href="{{ url_for('main.records') }}">
              Records
            </a>
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">
                More
              </a>
              <div class="navbar-dropdown">
                <a class="navbar-item" href="http://wiki.motorsports.illinois.edu/display/EL/Lap+Trigger+2021-2022">
                  About
                </a>
                <hr class="navbar-divider">
                <a class="navbar-item" href="{{ url_for('main.issue') }}">
                  Report an issue
                </a>
              </div>
            </div>
          </div>
      
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="buttons">
                {% if not current_user.is_authenticated %}
                <a class="button is-light" href="{{ url_for('auth.login') }}">
                  Log in
                </a>
                {% endif %}
                {% if current_user.is_authenticated %}
                  <a class="button is-danger" href="{{ url_for('auth.logout') }}">
                    Logout
                  </a>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </nav>
    </div>
    {% block content %}{% endblock %}
</body>
</html>

lapapp/templates/live.html
{% extends "base.html" %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='dataTables.bulma.min.css') }}">
<script src="{{ url_for('static', filename='jquery.dataTables.min.js') }}"></script>
<script src="{{ url_for('static', filename='dataTables.bulma.min.js') }}"></script>
<script src="{{ url_for('static', filename='live.js') }}"></script>
<div class="container">
    <div class="box">
        <div class="row">
            <div class="col-4">
                <table id="lapdata" class="table is-striped" style="width:100%">
                    <thead>
                        <tr>
                            <th>name</th>
                            <th>position</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

lapapp/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
        {% endif %} 
        {% endwith %}
        <form method="POST" action="/login">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="name" name="name" placeholder="Your Username" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Your Password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox">
                    Remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}